# Change these first
owner: Neustrashimy # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Nagoyadon.jp
    url: https://nagoyadon.jp
  - name: md.objektiv2.net
    url: https://md.objektiv2.net/web/timelines/home

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Services health monitor
  introTitle: ""
  introMessage: Powered by [upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
